categories:
  - title: '🚀 Features'
    when:
      labels:
        - 'feature'
        - 'feat'
        - 'enhancement'
        - 'enh'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
  - title: '🧰 Maintenance'
    when:
      labels:
        - 'chore'
        - 'dependencies'
template: |
  # What’s Changed

  $CHANGES
