run:
  timeout: 10m
issues:
  exclude-files:
    - "generated.*\\.go$"
linters:
  enable:
    - gci
    - goconst
    - gofmt
    - goimports
    - unparam
    - importas
    - bodyclose
    - containedctx
    - contextcheck
    - errorlint
    - nilerr
    - promlinter
    - sloglint
    - testifylint
    - unparam
    - usestdlibvars
    - revive
    - godot
linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/qdrant) # Custom section: groups all imports with the specified Prefix (our company, but our own component).
      - prefix(github.com/qdrant/terraform-provider-qdrant-cloud/) # Custom section: groups all imports with the specified Prefix (this component).
  importas:
    alias:
      - pkg: ^k8s\.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)$
        alias: $1$2
  revive:
    rules:
      - name: exported