# https://github.com/go-swagger/go-swagger/blob/master/docs/reference/templates/template_layout.md
layout:
  application:
    # https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/facade.gotmpl
    - name: facade
      source: asset:clientFacade
      target: "{{ joinFilePath .Target .ClientPackage }}"
      file_name: "{{ .Name }}_client.go"
    - name: qcmain
      source: "main.gtpl"
      target: "{{ joinFilePath .Target }}"
      file_name: "main.go"
    - name: provider
      source: "provider.gtpl"
      target: "{{ joinFilePath .Target }}/qdrantcloud"
      file_name: "provider.go"
    - name: utils
      source: "utils.gtpl"
      target: "{{ joinFilePath .Target }}/qdrantcloud/utils"
      file_name: "helper_functions.go"
    - name: provider_errors
      source: "errors.gtpl"
      target: "{{ joinFilePath .Target }}/qdrantcloud"
      file_name: "errors.go"
    - name: datadump
      source: "datadump.gtpl"
      target: "{{ joinFilePath .Target }}/data_profile"
      file_name: "application.profile"
  models:
    - name: definition
      source: asset:model
      target: "{{ joinFilePath .Target .ModelPackage }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
    - name: schemas
      source: "schemas.gtpl"
      target: "{{ joinFilePath .Target }}/qdrantcloud/schemas"
      file_name: "{{ camelize .Name }}_schema.go"
    - name: datadump
      source: "datadump.gtpl"
      target: "{{ joinFilePath .Target }}/data_profile"
      file_name: "{{ camelize .Name }}_models.txt"
  operations:
    # https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/parameter.gotmpl
    - name: api_parameters
      source: asset:clientParameter
      target: "{{ joinFilePath .Target .ClientPackage .Package }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_parameters.go"
    - name: api_responses
      source: "responses.gtpl"
      target: "{{ joinFilePath .Target .ClientPackage .Package }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_responses.go"
    - name: datadump
      source: "datadump.gtpl"
      target: "{{ joinFilePath .Target }}/data_profile"
      file_name: "operations.profile"
  operation_groups:
    # https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/client.gotmpl
    - name: client
      source: asset:clientClient
      target: "{{ joinFilePath .Target .ClientPackage .Name }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_client.go"
    - name: resources
      source: "resources.gtpl"
      target: "{{ joinFilePath .Target }}/qdrantcloud/resources"
      file_name: "{{ camelize .Name }}_resource.go"
    - name: datadump
      source: "datadump.gtpl"
      target: "{{ joinFilePath .Target }}/data_profile"
      file_name: "operation_groups.profile"
