/*
Qdrant Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qdrant_cloud_programmatic_access

import (
	"encoding/json"
	"fmt"
)

// QdrantErrorCode - Error codes internal to the API
type QdrantErrorCode struct {
	String *string
}

// stringAsQdrantErrorCode is a convenience function that returns string wrapped in QdrantErrorCode
func StringAsQdrantErrorCode(v *string) QdrantErrorCode {
	return QdrantErrorCode{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *QdrantErrorCode) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(QdrantErrorCode)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(QdrantErrorCode)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src QdrantErrorCode) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *QdrantErrorCode) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableQdrantErrorCode struct {
	value *QdrantErrorCode
	isSet bool
}

func (v NullableQdrantErrorCode) Get() *QdrantErrorCode {
	return v.value
}

func (v *NullableQdrantErrorCode) Set(val *QdrantErrorCode) {
	v.value = val
	v.isSet = true
}

func (v NullableQdrantErrorCode) IsSet() bool {
	return v.isSet
}

func (v *NullableQdrantErrorCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQdrantErrorCode(val *QdrantErrorCode) *NullableQdrantErrorCode {
	return &NullableQdrantErrorCode{value: val, isSet: true}
}

func (v NullableQdrantErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQdrantErrorCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


