/*
Qdrant Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qdrant_cloud_programmatic_access

import (
	"encoding/json"
	"fmt"
)

// QdrantClusterStateNodesValue struct for QdrantClusterStateNodesValue
type QdrantClusterStateNodesValue struct {
	QdrantClusterNodeState *QdrantClusterNodeState
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *QdrantClusterStateNodesValue) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into QdrantClusterNodeState
	err = json.Unmarshal(data, &dst.QdrantClusterNodeState);
	if err == nil {
		jsonQdrantClusterNodeState, _ := json.Marshal(dst.QdrantClusterNodeState)
		if string(jsonQdrantClusterNodeState) == "{}" { // empty struct
			dst.QdrantClusterNodeState = nil
		} else {
			return nil // data stored in dst.QdrantClusterNodeState, return on the first match
		}
	} else {
		dst.QdrantClusterNodeState = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(QdrantClusterStateNodesValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *QdrantClusterStateNodesValue) MarshalJSON() ([]byte, error) {
	if src.QdrantClusterNodeState != nil {
		return json.Marshal(&src.QdrantClusterNodeState)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableQdrantClusterStateNodesValue struct {
	value *QdrantClusterStateNodesValue
	isSet bool
}

func (v NullableQdrantClusterStateNodesValue) Get() *QdrantClusterStateNodesValue {
	return v.value
}

func (v *NullableQdrantClusterStateNodesValue) Set(val *QdrantClusterStateNodesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableQdrantClusterStateNodesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableQdrantClusterStateNodesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQdrantClusterStateNodesValue(val *QdrantClusterStateNodesValue) *NullableQdrantClusterStateNodesValue {
	return &NullableQdrantClusterStateNodesValue{value: val, isSet: true}
}

func (v NullableQdrantClusterStateNodesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQdrantClusterStateNodesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


